### ISSUE TITLE
Possible bug in findSectionByName

### ISSUE THREAD

**Issue by travitch** [GaloisInc/elf#2]
I am using `findSectionByName` to pull out the `.text` section from binaries and the latest round of changes seems to have caused some breakage.  It now seems to go into an infinite loop of allocations before I have to kill it.  If I change the implementation back to using `findOf`, everything works as expected.

I haven't dug into the actual cause yet.

**Comment by joehendrix** [comment]
Thanks for letting me know.  I added some strictness annotations, and
perhaps that resulted in the break.

**Comment by joehendrix** [comment]
I think this should be fixed now.  Elf reading and writing code no longer depends on lazyness.
